sudo: required
language: node_js
node_js:
- "7"
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

cache: yarn

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
- export PATH="$HOME/.yarn/bin:$PATH"

script:
- yarn install
- yarn build

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=wallbase/wallbase-app-ui
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

